### ISSUE TITLE
Ubuntu version compatibility not updated?

### ISSUE THREAD

**Issue by timginn** [pivpn/pivpn.github.io#2]
Under "Flexible" heading there is the statement "Although this is geared toward running on a $35 Raspberry Pi, the installer will work just as well on an Ubuntu Server running Trusty Tahr 14.04". The installation script itself at https://raw.githubusercontent.com/pivpn/pivpn/master/auto_install/install.sh says "Currently this installer supports Raspbian jessie, Ubuntu 14.04 (trusty), and Ubuntu 16.04 (xenial).".

If Ubuntu 16.04 really is supported, it would probably be best for the site to mention this, rather than only mentioning 14.04. Thank you.

**Comment by 4s3ti** [comment]
this has been fixed, 
Already on test branch and live on https://pivpn.dev

going to close when test is merged to master.

**Comment by 4s3ti** [comment]
its fixed and live. 
main branch for pivpn.dev: https://github.com/pivpn/pivpn.github.io/tree/pivpn.dev
