### ISSUE TITLE
Site is not served over HTTPS

### ISSUE THREAD

**Issue by IanOliver** [pivpn/pivpn.github.io#5]
The pivpn.io site is not securely served, allowing a MitM attacker to modify the page (eg. replace the bash command with something else).

For a quick fix, the site could be served via Cloudflare - see https://httpsiseasy.com/

However, ideally the domain itself should be setup with HTTPS (regardless of using Cloudflare). See https://blog.github.com/2018-05-01-github-pages-custom-domains-https/

**Comment by colinbrislawn** [comment]
I agree! Serving the site over https is a great way to lead by example. 🔐

Let us know how we can help get this set up.

**Comment by 4s3ti** [comment]
Site is being moved over to https://pivpn.dev 
Its fully working now! 
@orazioedoardo @james-lasersoft 
I have made some changes in the content.. please take a look at it and come back if you want me to change something before moving test branch over to master.

all is going to be opensourced ...Dockerfile, Dockerimage, nginx configs.

Images are hosted on my servers on High availability docker warm setup

**Comment by IanOliver** [comment]
Great news, thanks @4s3ti!

I've just submitted a pull request regarding the insecure Google Fonts import. That will fix the fonts not being rendered and the browser console errors.

**Comment by 4s3ti** [comment]
thanks @IanOliver 
Just accepted it =)

**Comment by IanOliver** [comment]
Perfect, thanks!

**Comment by 4s3ti** [comment]
Site has been moved to https://pivpn.dev
Site is now being served over https! 
Changed pivpn.io to inform users about the move.
